// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AcceptBtn: typeof import('./src/components/AcceptBtn.vue')['default']
    CullingPage: typeof import('./src/components/CullingPage.vue')['default']
    ExpandClusterBtn: typeof import('./src/components/expandClusterBtn.vue')['default']
    ImageCard: typeof import('./src/components/ImageCard.vue')['default']
    ImageUploadArea: typeof import('./src/components/ImageUploadArea.vue')['default']
    UploadImagesPage: typeof import('./src/components/UploadImagesPage.vue')['default']
    VerticalClusters: typeof import('./src/components/VerticalClusters.vue')['default']
    WelcomePage: typeof import('./src/components/WelcomePage.vue')['default']
  }
}

export { }
