// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AcceptBtn: typeof import('./components/AcceptBtn.vue')['default']
    CullingPage: typeof import('./components/CullingPage.vue')['default']
    ExpandClusterBtn: typeof import('./components/expandClusterBtn.vue')['default']
    ImageUploadBtn: typeof import('./components/ImageUploadBtn.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
