// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AcceptBtn: typeof import('./components/AcceptBtn.vue')['default']
    CullingPage: typeof import('./components/CullingPage.vue')['default']
    ExpandClusterBtn: typeof import('./components/expandClusterBtn.vue')['default']
    ImageUploadArea: typeof import('./components/ImageUploadArea.vue')['default']
    README: typeof import('./components/README.md')['default']
    UploadImagesPage: typeof import('./components/UploadImagesPage.vue')['default']
    VerticalClusters: typeof import('./components/VerticalClusters.vue')['default']
    WelcomePage: typeof import('./components/WelcomePage.vue')['default']
  }
}

export { }
